/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Timestamp = bigint;
export interface TruckStop {
  'id' : bigint,
  'totalShowers' : bigint,
  'city' : string,
  'chain' : string,
  'name' : string,
  'lastUpdated' : Timestamp,
  'highway' : string,
  'state' : string,
  'availableShowers' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateTruckStop' : ActorMethod<
    [[] | [bigint], string, string, string, string, string, bigint],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllTruckStops' : ActorMethod<[], Array<TruckStop>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTruckStopById' : ActorMethod<[bigint], TruckStop>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeTruckStop' : ActorMethod<[bigint], undefined>,
  'searchTruckStops' : ActorMethod<[string], Array<TruckStop>>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'updateShowerAvailability' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];