/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const TruckStop = IDL.Record({
  'id' : IDL.Nat,
  'totalShowers' : IDL.Nat,
  'city' : IDL.Text,
  'chain' : IDL.Text,
  'name' : IDL.Text,
  'lastUpdated' : Timestamp,
  'highway' : IDL.Text,
  'state' : IDL.Text,
  'availableShowers' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateTruckStop' : IDL.Func(
      [
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllTruckStops' : IDL.Func([], [IDL.Vec(TruckStop)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTruckStopById' : IDL.Func([IDL.Nat], [TruckStop], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeTruckStop' : IDL.Func([IDL.Nat], [], []),
  'searchTruckStops' : IDL.Func([IDL.Text], [IDL.Vec(TruckStop)], ['query']),
  'seedSampleData' : IDL.Func([], [], []),
  'updateShowerAvailability' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const TruckStop = IDL.Record({
    'id' : IDL.Nat,
    'totalShowers' : IDL.Nat,
    'city' : IDL.Text,
    'chain' : IDL.Text,
    'name' : IDL.Text,
    'lastUpdated' : Timestamp,
    'highway' : IDL.Text,
    'state' : IDL.Text,
    'availableShowers' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateTruckStop' : IDL.Func(
        [
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllTruckStops' : IDL.Func([], [IDL.Vec(TruckStop)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTruckStopById' : IDL.Func([IDL.Nat], [TruckStop], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeTruckStop' : IDL.Func([IDL.Nat], [], []),
    'searchTruckStops' : IDL.Func([IDL.Text], [IDL.Vec(TruckStop)], ['query']),
    'seedSampleData' : IDL.Func([], [], []),
    'updateShowerAvailability' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };